version: "3.2"
services:
  mysql:
    image: "mysql:5.6"
    environment:
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "pass1"
      MYSQL_DATABASE: "surldb"
      MYSQL_ROOT_PASSWORD: "pass1"
    networks:
      - backend
  microservice:
    build: .
    volumes:
      - ./log:/app/log
    environment:
      AUTHOR: "anupampathi"
    command: [ "gunicorn","-c","python:config.gunicorn","surl.app:create_app()" ]
    depends_on:
      - "mysql"
    networks:
      - backend
  nginx:
    image: "nginx:1.20"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - microservice
      - mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge